GB-Zone/Controllers/ViabilityDataCollectionController.cs
using GrinGlobal.Zone.Helpers.controllerBL;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Xml.Linq;

namespace GrinGlobal.Zone.Controllers
{
    public class ViabilityDataCollectionController : CoreController
    {
        private ViabilityDataCollectionBL bl;

        /// <summary>
        /// Constructor to load parent constructor
        /// </summary>
        public ViabilityDataCollectionController() : base()
        {

        }
        #region public function
        /// <summary>
        /// First step to create the module for Viability Data Collection
        /// </summary>
        /// <param name="moduleId">Id module from settings.xml</param>
        /// <param name="formId">Id form from settings.xml</param>
        /// <returns>Page viability Data Collection</returns>
        // GET: ViabilityDataCollection
        public ActionResult Index(string moduleId, string formId)
        {
            Init(moduleId, formId);
            DataSet ds = DataInit(moduleId, formId, new DataSet());
            return View(ds);
        }

        /// <summary>
        /// Serach from Inventory Viability, form create or update inventory viability data
        /// </summary>
        /// <param name="formC">Form data from web</param>
        /// <returns>Json with the information from experiment</returns>
        [HttpPost]
        public JsonResult SearchInventory(FormCollection formC)
        {
            Init();
            DataSet datS = new DataSet();
            bl = new ViabilityDataCollectionBL(sopH);
            try
            {
                jResponse.DataJson = bl.AddDictionaryAll(formC, new Dictionary<string, object>());
                jResponse.Success = 200;
            }
            catch (Exception ex)
            {
                jResponse.MenssageError = ex.Message;
            }
            return jResponse.GetJsonResult(sopH.SetH.GlobalMaxJsonLength);
        }

        /// <summary>
        /// Save the data, form invneotry viability data and testd_date of inventory viability
        /// </summary>
        /// <param name="formC">Form data from web</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Save(FormCollection formC)
        {
            Init();
            DataSet datS = new DataSet();
            bl = new ViabilityDataCollectionBL(sopH);
            try
            {
                bl.Save(formC);
                jResponse.Success = 200;
            }
            catch (Exception ex)
            {
                jResponse.Success = 500;
                jResponse.MenssageError = ex.Message;
            }
            return jResponse.GetJsonResult(sopH.SetH.GlobalMaxJsonLength);
        }
        /// <summary>
        /// Obtain the grid with information on all the viability inventory data  from the inventory identifier of the experiment.
        /// </summary>
        /// <param name="formC">Form data from web</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GridViewInventoryViabilityData(FormCollection formC)
        {
            Init();
            DataSet datS = new DataSet();
            bl = new ViabilityDataCollectionBL(sopH);
            try
            {
                datS = bl.GridViewInventoryViabilityData(formC);
            }
            catch (Exception ex)
            {
                ViewData[hHelp.SYS_VIEWDATA_EDIT_ERROR] = ex.Message;
            }
            SetViewData(bl.DicDataView);
            return PartialView("_GridReadOnlyPartitial", datS);
        }

        /// <summary>
        /// Obtain the grid with information on all hisotry from the viability inventory.
        /// </summary>
        /// <param name="formC">Form data from web</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult GridViewInventoryViability(FormCollection formC)
        {
            Init();
            DataSet datS = new DataSet();
            bl = new ViabilityDataCollectionBL(sopH);
            try
            {
                datS = bl.GridViewInventoryViability(formC);
            }
            catch (Exception ex)
            {
                ViewData[hHelp.SYS_VIEWDATA_EDIT_ERROR] = ex.Message;
            }
            SetViewData(bl.DicDataView);
            return PartialView("_GridReadOnlyPartitial", datS);
        }
        [HttpPost]
        public JsonResult ValidateCooperateId(FormCollection formC)
        {
            Init();
            DataSet datS = new DataSet();
            bl = new ViabilityDataCollectionBL(sopH);
            try
            {
                DataRow cooperatorRow = bl.ValidateCooperatorId(formC);
                if (cooperatorRow != null)
                {
                    jResponse.DataJson = new Dictionary<string, object>()
                    {
                        {"cooperator", cooperatorRow },
                    };
                    jResponse.Success = 200;
                }
                else
                {
                    jResponse.Success = 400;
                }
            }
            catch (Exception ex)
            {
                jResponse.Success = 500;
                jResponse.MenssageError = ex.Message;
            }
            return jResponse.GetJsonResult(sopH.SetH.GlobalMaxJsonLength);
        }
        #endregion

        #region protected function
        protected override DataSet DataInit(string moduleId, string formId, DataSet datS)
        {
            base.DataInit(moduleId, formId, datS);
            XElement node = sopH.SetH.GetField_AtributeValue(hHelp.SYS_VIABILITYDATACOLLECTION_FIELDNAME_SCANDQR);
            ViewData[hHelp.SYS_VIABILITYDATACOLLECTION_FIELDNAME_SCANDQR] = node.Attribute(sopH.SetH.SETTING_NAME_GENERIC_ID).Value;
            ViewBag.MenuTitle = "Viability";
            ViewBag.MenuTitleInfo = "Viability data collection";
            ViewBag.SearchTitle = "Scan inventory_viability_data_id to set the test information";
            return datS;
        }
        #endregion
    }
}

GB-Zone/Views/ViabilityDataCollection/ComponentDataCollectionPartitial.cshtml
<div class="content" id="divContendCampureData">
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel" id="divHPanelGeneralData">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    Inventory information:
                </div>
                <div class="panel-body" style="display: block;">
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputInventoryNumber">Inventory Number: </label>
                            <input type="text" id="inputInventoryNumber" class="form-control" readonly />
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputReplicante">Replicante:</label>
                            <input id="inputReplicante" type="text" class="form-control" readonly />
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputReplicanteinventory_viability_id_readonly">Inventory viability id:</label>
                            <input id="inventory_viability_id_readonly" type="text" class="form-control" readonly />
                        </div>
                    </div>
                    <div class="row border-top">
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputAccesion">Accesion: </label>
                            <input id="inputAccesion" class="form-control" type="text" readonly />
                        </div>
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputAccesionName">Accesion name:</label>
                            <input id="inputAccesionName" class="form-control" readonly type="text" />
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputTaxonomy">Taxonomy:</label>
                            <input id="inputTaxonomy" class="form-control" readonly type="text" />
                        </div>
                    </div>
                    <div class="row border-top">
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputNameRule">Viability rule:</label>
                            <input id="inputNameRule" class="form-control" type="text" readonly />
                        </div>
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputNumberReplicanteRule">Number of Replicantes:</label>
                            <input id="inputNumberReplicanteRule" class="form-control" type="text" readonly />
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputSeedPerReplicateRule">Seeds per replicate:</label>
                            <input id="inputSeedPerReplicateRule" class="form-control" type="text" readonly />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputStartingDate">Starting date: </label>
                            <input id="inputStartingDate" type="date" class="form-control" />
                        </div>
                        <div class="col-lg-4 col-sm-4 border-right form-group">
                            <label for="inputCountDate">Count date: </label>
                            <input id="inputCountDate" type="date" readonly class="form-control" />
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputDay">Days:</label>
                            <input id="inputDay" type="number" readonly class="form-control" />
                        </div>
                        <input id="inventory_viability_id" type="hidden" />
                        <input id="inventory_id" type="hidden" />
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel" id="divHPanelCountData">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhide"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    Data Collection
                </div>
                <div class="panel-body" style="display: block;">
                    <div class="row">
                        <div class="col-lg-4 col-sm-4" id="divReplicanteNumber" style="font-size:large; font-weight:bold">
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputCooperatorId">Cooperator:</label>
                            <input class="form-control" type="number" id="inputCooperatorId" aria-describedby="cooperatorIdHelp" />
                            <small id="cooperatorIdHelp" class="form-text text-muted"></small>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputCountAbnormal">Abnormal:</label>
                            <input class="form-control" type="number" id="inputCountAbnormal" min="0" pattern="^[0-9]+" />
                        </div>
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputCountDead">Dead:</label>
                            <input class="form-control" type="number" id="inputCountDead" min="0" pattern="^[0-9]+" />
                        </div>
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputCountDormant">Dormant:</label>
                            <input class="form-control" type="number" id="inputCountDormant" min="0" pattern="^[0-9]+" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputCountInfested">Infested:</label>
                            <input class="form-control" type="number" id="inputCountInfested" min="0" pattern="^[0-9]+" />
                        </div>
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputCountEmpty">Empty:</label>
                            <input class="form-control" type="number" id="inputCountEmpty" min="0" pattern="^[0-9]+" />
                        </div>
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputCountUnknown">Unkown:</label>
                            <input class="form-control" type="number" id="inputCountUnknown" min="0" pattern="^[0-9]+" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 form-group">
                            <label for="inputCountHard">Hard:</label>
                            <input class="form-control" type="number" id="inputCountHard" min="0" pattern="^[0-9]+" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12 form-group">
                            <label for="inputNote">Note:</label>
                            <input class="form-control" type="text" id="inputNote" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputCountNormal">Normal:</label>
                            <input class="form-control" type="number" id="inputCountNormal" readonly />
                        </div>
                        <div class="col-lg-4 col-sm-4 bottom-right form-group">
                            <label for="inputGermination">Germination %:</label>
                            <input class="form-control" type="number" id="inputGermination" readonly />
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-2 col-sm-2 text-left">
                            <input class="btn btn-success" type="button" id="buttonSave" value="SAVE" />
                        </div>
                        <div class="col-lg-8 col-sm-8 text-left">
                            <input class="btn btn-info" type="button" id="buttonClear" value="CLEAR" />
                        </div>
                        <div class="col-lg-2 col-sm-2 text-right">
                            <input class="btn btn-danger" type="button" id="buttonDelete" value="CANCEL" />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel" id="divHpanelInventoryViabilityData">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhidegrid" id="aHpanelInventoryViabilityData"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    Inventory Viability Data
                </div>
                <div class="panel-body" style="display: block;">
                    <div class="row" id="divInventoryViabilityData">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="hpanel" id="divHpanelViabilityHistory">
                <div class="panel-heading">
                    <div class="panel-tools">
                        <a class="showhidegrid" id="aHpanelViabilityHistory"><i class="fa fa-chevron-up"></i></a>
                    </div>
                    Viability History
                </div>
                <div class="panel-body" style="display: block;">
                    <div class="row" id="divInventoryViability">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GB-Zone/Views/ViabilityDataCollection/Index.cshtml
@model System.Data.DataSet
@using GrinGlobal.Zone.Helpers.setting
<!-- ViabilityDataCollection/Index -->
@{
    HtmlHelp hHelp = new HtmlHelp();
    string fieldQR = ViewData[hHelp.SYS_VIABILITYDATACOLLECTION_FIELDNAME_SCANDQR].ToString();
}

@{
    ViewBag.ViewTitle = "| " + ViewData[hHelp.SYS_VIEWDATA_MODULEID];
}
<script type="text/javascript">
    var urlSearch = '@Url.Action("SearchInventory", "ViabilityDataCollection")';
    var fieldQR = '@fieldQR';
    var urlSave = '@Url.Action("Save", "ViabilityDataCollection")';
    var urlGridInventoryViabilityData = '@Url.Action("GridViewInventoryViabilityData", "ViabilityDataCollection")';
    var urlGridInventoryViability = '@Url.Action("GridViewInventoryViability", "ViabilityDataCollection")';
    var urlValidateCooperateId = '@Url.Action("ValidateCooperateId", "ViabilityDataCollection")';
</script>

@Scripts.Render("~/bundles/viabilitydatacollection/js")

@Html.Partial(hHelp.SYS_RAZO_GENERICINDEX, Model, new ViewDataDictionary(ViewData))


<div class="row">
    @Html.Partial("ComponentDataCollectionPartitial", Model, new ViewDataDictionary(ViewData))
</div>